[package]
name = "rustai"
version = "0.1.0"
authors = ["de"]

[lib]
name = "rustai"
crate-type = ["dylib"]

[dependencies.cpython]
git = "https://github.com/dgrunwald/rust-cpython.git"
#default-features = false
#features = ["python27-sys"]
